### ISSUE TITLE
Please stop including cockpit's deprecated bundled jquery

### ISSUE THREAD

**Issue by martinpitt** [hellcatz/zcash-cli-cockpit#2]
This project currently uses jquery from cockpit:

     <script type="text/javascript" src="../base1/jquery.js"></script>

Please stop doing that and include your own from npmjs.org instead. If you rely on a particular jQuery version, this might break underneath you. Please see https://lists.fedorahosted.org/archives/list/cockpit-devel@lists.fedorahosted.org/thread/TDBKI4372I4ZPGQFCZB377DX2QG2YDDY/ for more information.

Particularly, cockpit will update to jQuery 3.0 soon (https://github.com/cockpit-project/cockpit/pull/8505) which has quite a lot of changes, see the [upgrade guide](https://jquery.com/upgrade-guide/3.0/).

**Comment by martinpitt** [comment]
To clarify: This was not really your fault, but entirely our's -- sorry if the wording indicated otherwise. Cockpit's own examples and documentation included this (which got fixed now), but it's a potential breakage for any external cockpit extensions, so this needs to be cleaned up.

Thanks!

**Comment by hellcatz** [comment]
Thank you for reaching out to my little project.
I have updated code in this commit https://github.com/hellcatz/zcash-cli-cockpit/pull/1/commits/c4c29b19e9c4e85a2aa80f704dff8e2591c39b1c in pending PR from multi-coin branch.
